title: jekyll-theme-instagram
name: Jekyll Theme Instagram
description: 'A minimalist Jekyll theme for creating an Instagram-inspired user profile page.'
url: https://diptanil.page
baseurl: "/jekyll-theme-instagram"
header_img: /media/jekyll-theme-instagram.png

ig_username: 
ig_category: Jekyll Theme
ig_website: github.com/diptanilsaha/jekyll-theme-instagram/

footer_website: diptanil.page

favicon: /media/favicon.ico

remote_theme: diptanilsaha/jekyll-theme-instagram

theme_config:
  archive: true

include:
  - media

sass:
  style: :compressed
